### ISSUE TITLE
Maven release

### ISSUE THREAD

**Issue by Rebzie** [douglascrockford/JSON-java#125]
Hi

Just wondering if there is going to be a maven release. There is another project which has published to maven but not for 2 years and the naming isn't standard
https://github.com/eskatos/org.json-java/releases

**Comment by stleary** [comment]
Maven support has been proposed before and declined. For example, https://github.com/douglascrockford/JSON-java/pull/46, https://github.com/douglascrockford/JSON-java/pull/35, https://github.com/douglascrockford/JSON-java/pull/21, etc. I don't expect that to change anytime soon.

**Comment by johnjaylward** [comment]
I think this request is a little different than those, I believe Rebzie is requesting that a jar be pushed to Maven Central or other repo to be included as a library in a project.

**Comment by stleary** [comment]
Thanks for clarifying, I missed that. No such plans that I am aware of.

**Comment by Haringat** [comment]
If you pull it #131 would fix that automatically.

**Comment by johnjaylward** [comment]
no, it won't be automatic. You still need publishing keys or "approved" hosting and release information for it to be automatic.

see: http://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by stleary** [comment]
Sorry for not getting back to this sooner. At the present time this project does not include support for any particular build tool.
