### ISSUE TITLE
json with "content" attribute name causes XML.toString() to fail

### ISSUE THREAD

**Issue by kleebiz** [douglascrockford/JSON-java#137]
If you have an attribute name of "content", XML.toString(json) will fail.  Workaround is to change XML class to use an more unique identifier other than "content".

{"Profile": { "list": {"history": { "entries": [{"deviceId": "id","content": {"material": [{"stuff": false}]}}]}}}}

**Comment by stleary** [comment]
Thanks for pointing this out. I don't think changing the "content" keyword can happen due to the risk of breaking working code. But at least the API could clearly spell out how and why it is used. So this will be a documentation-only change. Post a comment if you want to work on it.

**Comment by gillettelevi5** [comment]
Null

**Comment by stleary** [comment]
I don't think this rises to the level of a must-fix bug at this time.
