### ISSUE TITLE
Stackoverflow when creating JSONObject from an object with a getter which is returning itself

### ISSUE THREAD

**Issue by saral** [douglascrockford/JSON-java#141]
Calling 
`new JSONObject(new RecursiveObject());`

results in StackOverflow.

```
public static class RecursiveObject {
	public RecursiveObject getCurrent() {
		return this;
	}
}
```

**Comment by douglascrockford** [comment]
Warning: This method assumes that the data structure is acyclical.

**Comment by saral** [comment]
Can we just ignore the cyclical getters? I made a pull request for this, it would be really useful in our case.

**Comment by johnjaylward** [comment]
you would have to keep a map of all pulled objects to know if it was cyclical at any given depth. It's easier to just create a mapped object that does not hold a cyclical relationship and pass that to the constructor.

**Comment by saral** [comment]
Yes deeper levels should also be handled (which is an easy task). But if you want to keep it like this, than I would suggest to find a way of at least not causing a Stackoverflow, which is a very bad situation. And I think this precondition (not allowing cyclic data structures) should be in the javadoc of this particular constructor. Anyways thank you for your replies.

**Comment by stleary** [comment]
If you want to change the current behavior, you need to make a compelling case that the code, as opposed to the inputs, is wrong. Otherwise, to change the documentation, please help us get on the same page by providing a concrete use case that demonstrates how this input is problematic and propose whatever Javadoc text you feel will best address it.

**Comment by johnjaylward** [comment]
I'm not sure why you think this is an easy task for handling an any depth cycle. If my object looks like this:
A->B->C->D->A I wouldn't know it cycled back until I get to D. 

You would either have to kill it at an arbitrary depth, or keep a mapping of what has been mapped in the current object branch and make sure you don't reference anything in the tree structure.

The first method would break compatibility with existing programs, and the second method would add a memory and performance overhead that may not be wanted.

I think just updating the documentation is the proper course of action here and users should sanitize their object inputs in advance.
