### ISSUE TITLE
JSONObject.wrap does not handle enums

### ISSUE THREAD

**Issue by abewell** [douglascrockford/JSON-java#145]
Steps to reproduce:
Create a new JSONObject();
try to add an enum as a value
dump the jsonObject via the toString() method

expected:
we see the enum values

actual:
we do not see the enum values

Please see below stack. It seems that the JSONObject.wrap function fails to recognize the enum and tries to use the bean constructor from the JSONObject class. My enum does not have getters/setters like (since it is not a bean) and so nothing gets dumped from the toString()

JSONObject.wrap(Object) line: 1730	
JSONArray.<init>(Collection<Object>) line: 159	
JSONObject.writeValue(Writer, Object, int, int) line: 1767	
JSONObject.write(Writer, int, int) line: 1836	
JSONObject.toString(int) line: 1614	
JSONObject.toString() line: 1591	
JSONOutputRenderer.buildVariantsArray(Set<VariantInfo>) line: 100	
JSONOutputRenderer.getJson(BuildInfo) line: 83	
JSONOutputRenderer.generateBuildInfo(String, BuildInfo) line: 50	
GenBuildOutputHandlerMain.outputBuildInfo(String, BuildInfo) line: 24	
GenBuildOutputHandlerMain.processFile(String) line: 18	
GenBuildOutputHandlerMain.main(String[]) line: 34

I have pulled the latest source and built the following suggestion to fix the bug:

Added at line 1722 of JSONObject.java
            if(object instanceof Enum){
                return object.toString();
            }

**Comment by stleary** [comment]
Thanks for pointing this out. Some explicit support for enum was added a few weeks ago. Please see the discussion in https://github.com/douglascrockford/JSON-java/pull/127. At the time, wrap() was mentioned but not included in the final list. Based on the constraints in the discussion thread, if you think you see a way that wrap() support for enum could be allowed, please let us know your ideas. Will leave this issue open a few days for feedback.

**Comment by abewell** [comment]
Ah yeah, I read through your mentioned discussion. I see that it is more ambiguous than my simple case was. I don't usually use enums with getters/setters, but I can see how it would make sense too. I can't think of anything more than what you all already discussed for a general solution. So I'm not sure what the appropriate fix for this project would be. I will plan to just stick with my one off case for now. Thanks for pointing me to that thread. Take care.

**Comment by stleary** [comment]
Closing this issue for now. Future pull requests to provide additional support for enum are welcome, but we need to be able to confirm that no problems will be caused for existing applications. Please see unit test https://github.com/stleary/JSON-Java-unit-test/blob/master/EnumTest.java for examples of how enum is currently supported.
