### ISSUE TITLE
enum serialization

### ISSUE THREAD

**Issue by gullerya** [douglascrockford/JSON-java#147]
Hi,
I'm using this lib for a simple map-like POJOs serialization and found that Enum fields are serialized to something like "size = 0".
Am i missing something ot is it not fully supported yet (looked into the JSONObject and actually saw no explicit treatment for Enum, so I assume that this cases fail into the 'instanceof Object' and processed like regular Object; I do see deserialization code though)?

One more thing: is it (will it be) possible to explicitly state alternative to OOTB valueOf method? And probably also the serialized value providing method? Something like @JsonValue and @JsonConstructor of javax?

**Comment by stleary** [comment]
Hi, 
You are correct, enums are handled as beans, and if an simple enum in a POJO is serialized, the results are not helpful. JSON-Java was written before Java enums were implemented, and changes to the existing API are rare. However, there should be a way to accomplish whatever you need to do with enums. Please see the test method comments in EnumTest.java in the unit tests (https://github.com/stleary/JSON-Java-unit-test/blob/master/EnumTest.java). If you still have questions about how to accomplish your goals, please post a code sample here.

To change OOTB behavior, annotations are not supported at the present time, so I guess the alternative is to extend or rewrite the classes. For specific changes or requests, a code sample would help.

Best regards,
Sean

**Comment by stleary** [comment]
No further actions are planned at this time.
