### ISSUE TITLE
when parse a valid   json string,.JSONException throws

### ISSUE THREAD

**Issue by DanielYuan2012** [douglascrockford/JSON-java#150]
package org.json;

public class parse_Json {
	
	
	public void parseJson3(String jsonString3) throws JSONException{
    	JSONObject obj=new JSONObject(jsonString3);
    	String name=obj.getString("name");
    	
    	System.out.println("Name is: "+name);
    	
    	JSONObject obj2=obj.getJSONObject("batters");
    	
    	//Here we get json array inside obj2 with key- batter
    	JSONArray array=obj2.getJSONArray("batter");
    	
    	//Getting json objects inside array
    	for(int i=0;i<array.length();i++){
    		JSONObject obj3=array.getJSONObject(i);
    		//Getting id and type of json objects inside array
    		System.out.println("Id of obj3 : "+obj3.getString("id")+" Type of obj3 : "+obj3.getString("type"));
    	}
    	
    	//Here we get json array inside obj1 with key- topping
    	JSONArray array2=obj.getJSONArray("topping");
    	
    	//Getting json objects inside array
    	for(int i=0;i<array2.length();i++){
    		JSONObject obj4=array2.getJSONObject(i);
    		//Getting id and type of json objects inside array2
    		System.out.println("Id of obj4 at index "+i+" is : "+obj4.getInt("id")+" Type of obj4 at index "+i+" is : "+obj4.getString("type"));
    	}
    	
    }

	public static void main(String[] args){
		//String jsonString ="{'schema': 'http://json.org/example','title': 'Product','description': 'A product from catalog','type': 'object','properties': {'id': {'description': 'The unique identifier for a product','type': 'integer'},'name': {'description': 'Name of the product','type': 'string'}},'required': ['id', 'name']}";
		parse_Json instance = new parse_Json();
		//instance.parseJson(jsonString);
		String jsonString2="{\"name\":\"Cake\",\"batters\":{\"batter\":[{\"id\":\"1001\",\"type\":\"Regular\"},{\"id\":\"1002\",\"type\":\"Chocolate\"},{\"id\":\"1003\",\"type\":\"Blueberry\"},{\"id\":\"1004\",\"type\":\"Devil\"s Food\"}]},\"topping\":[{\"id\":5001,\"type\":\"None\"},{\"id\":5002,\"type\":\"Glazed\"},{\"id\":5005,\"type\":\"Sugar\"},{\"id\":5007,\"type\":\"Powdered Sugar\"},{\"id\":5006,\"type\":\"Chocolate with Sprinkles\"},{\"id\":5003,\"type\":\"Chocolate\"},{\"id\":5004,\"type\":\"Maple\"}]}";
		//instance.parseJson2(jsonString2);
		instance.parseJson3(jsonString2);
	}
}

when execute this test program, the error below throw out:

Exception in thread "main" org.json.JSONException: Expected a ',' or '}' at 161 [character 162 line 1]
	at org.json.JSONTokener.syntaxError(JSONTokener.java:433)
	at org.json.JSONObject.<init>(JSONObject.java:233)
	at org.json.JSONTokener.nextValue(JSONTokener.java:364)
	at org.json.JSONArray.<init>(JSONArray.java:116)
	at org.json.JSONTokener.nextValue(JSONTokener.java:367)
	at org.json.JSONObject.<init>(JSONObject.java:218)
	at org.json.JSONTokener.nextValue(JSONTokener.java:364)
	at org.json.JSONObject.<init>(JSONObject.java:218)
	at org.json.JSONObject.<init>(JSONObject.java:325)
	at org.json.parse_Json.parseJson3(parse_Json.java:86)
	at org.json.parse_Json.main(parse_Json.java:122)

**Comment by stleary** [comment]
Please try running your JSON document through an online parser, e.g. http://www.jsonlint.com. I think you will find that the value in this name/value pair has an invalid escaped quote: \"type\":\"Devil\"s Food\".  If you change the \"s to something like 's, the document should parse correctly. If this does not fix the problem, please comment or open a new issue.
