### ISSUE TITLE
Update Readme for Number limitations

### ISSUE THREAD

**Issue by johnjaylward** [douglascrockford/JSON-java#162]
see #157 for discussion.

Neither http://json.org, nor this projects README references the RFC that allows limitations on numeric values. JSON.org references [ECMA-404 The JSON Data Interchange Standard](http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf) which leave the numbers open to exact values.

I propose that if we do not allow any number range, then we note in the README what the limitation on integer and double values are as well as link to the RFC : https://tools.ietf.org/html/rfc7159

**Comment by stleary** [comment]
Sounds reasonable. Do you want to propose any text for the README?

**Comment by johnjaylward** [comment]
At this point I'm too tired, it's past 1am for me. I'll think more on wording at a later date if you don't get to it first.

**Comment by stleary** [comment]
See https://github.com/douglascrockford/JSON-java/pull/186
