### ISSUE TITLE
Consider introducing a JSONValue class

### ISSUE THREAD

**Issue by matthijskooijman** [douglascrockford/JSON-java#163]
I've just started using this library to implement a JSON-RPC client. I like its simplicity, while also supporting reading JSON data incrementally from a stream, which seems isn't well supported in other libraries.

Anyway, when you access data in a map or array, you can easily convert it to some type, using e.g. `getDouble()`, `getJSONObject()`, `getString()`, etc. This allows for conveniently traversing a JSON value, without all kinds of conversion overhead. However, I have a bit of code that must return one field from a `JSONObject`, without knowing what type the caller of that code wants. Right now, this means I either have to return `Object` and let the caller sort it out the conversion, or I would somehow need to pass an extra argument to indicate what type is expected and call the corresponding `getXXX()` method (which is terribly cumbersome). I would have used generics to pass the type expected, but since generic types are erased at runtime, this won't help here.

Now, one alternative that I believe could help here, would be to define a `JSONValue` class, that can represent all various JSON values used (String, Long, Double, JSONObject, JSONArray) and can be easily converted using `asDouble()`, `asJSONObject()`, etc. methods. This class can be used instead of `Object` in `JSONArray`'s type, or `JSONObject.get()`'s return type, or it can just be left up to users to wrap a returned `Object` in a `JSONValue`.

By letting both `JSONArray` and `JSONObject` use the conversions functions from this new `JSONValue` class, some code duplication between them can be reduced as well (at the cost of one extra created object for each conversion, which can even be mitigated by moving the code into static methods on `JSONValue` and calling those from the normal methods in all three classes).

Does this sound reasonable? If so, I'll probably have a stab at making a PR for it.

**Comment by johnjaylward** [comment]
I personally don't see much benefit of it over an object. The caller still needs to know the type when it wants to use it. I don't see a big difference between what you are describing as a use-case, vs this:

```java
JSONObject jo = new JSONObject("{\"number\":123456789, \"string\":\"string Value!!!\", \"boolean\":true}, \"null\":null, \"object\":{\"o1\":\"o1String\"}, \"array\":[1,2,3] }");

Object os = jo.get("string");
Object ob = jo.get("boolean");

System.out.println(os.toString() + "\n" + ob.toString());

Object jn = jo.get("number");
if(jn instanceof Number){
   System.out.println("We have a number"+((Number)jn).longValue());
}
```

Forcing a JSONValue object into JSONArray instead of allowing any Object would cause more overhead as you are now wrapping everything which will have construction cost, stack overhead for function pointers, and stack overhead for pointing to the original object.


If we implemented JSONValue, I don't think the change would be as extensive as you are asking for. I would just have something like:
```java
public class JSONValue {
    private Object actualVal;
    // opt/get methods as in the JSONObject and JSONArray classes as well as a way to return the "actualVal"
}

public class JSONValueIterator implements Iterator<JSONValue> {
// constructor would take an existing iterator and Next would wrap the values in JSONValue
}
```
Then in JSONObject and JSONArray do something like this:

```java
public getJSONValue(String key) {
    return new JSONValue(this.opt(key));
}
```

The in only JSONArray do this:
```java
public JSONValueIterator iteratorJSONValue(){
    return new JSONValueIterator(this.iterator());
}
```

**Comment by stleary** [comment]
Intriguing idea, but not sure there is a place for it in this lib. You could try developing the idea and see if any good use cases emerge. But the JSON-java design and implementation is mostly settled, so a pull request will likely be declined.

**Comment by matthijskooijman** [comment]
Looking at your example, I agree that the difference is small. But
still, I would consider it an improvement if instead of this (error
handling added by me):

    Object jn = jo.get("number");
    if(jn instanceof Number){
       System.out.println("We have a number"+((Number)jn).longValue());
    } else {
        // Throw exception
    }

you could write this:

    JSONValue jn = jo.getJSONValue("number");
    System.out.println("We have a number"+jn.getLong());

The difference is more pronounced for other types, like boolean, where
you could shorten this:

    Object ob = jo.get("boolean");

    bool value;
    if (ob.equals(Boolean.FALSE)
            || (object instanceof String && ((String) object)
                    .equalsIgnoreCase("false"))) {
        value = false;
    } else if (object.equals(Boolean.TRUE)
            || (object instanceof String && ((String) object)
                    .equalsIgnoreCase("true"))) {
        value = true;
    } else {
        // Throw exception
    }

into this:

    JSONValue ob = jo.getJSONValue("boolean");
    bool value = ob.getBoolean();

Having said that, fully integrating this object will indeed add
overhead, and it's probably not really needed (Things can just be wrapped in JSONValue when needed).  Also, with the implementation you proposed, it could very
well be implemented on top of the library, not really needing any
changes in the library itself, so I'll go ahead and work on something in
my own application. If it comes to something, I'll post the code here
for evaluation - it might be useful to include it in the library as a
utility, or if nothing else to reduce the duplicate code between object
and array.

Thanks for you swift, detailed and clear responses!
