### ISSUE TITLE
Strange conversion from XML to JSON

### ISSUE THREAD

**Issue by gimmi** [douglascrockford/JSON-java#165]
Take the following code:

```java
System.out.println(XML.toJSONObject("<doc content='abc'>def</doc>"));
```

What i expect is this JSON

```json
{"doc":["abc","def"]}
```

Instead i get the following

```json
{"doc":[["abc","def"]]}
```

Is this a bug or is by design?

**Comment by douglascrockford** [comment]
"content" is reserved for unlabeled content.

**Comment by gimmi** [comment]
If it's reserved, wouldn't then be more appropriate to just don't consider "content" attribute?
