### ISSUE TITLE
XML.toString() need to handle invalid characters in nodeName

### ISSUE THREAD

**Issue by anilverma070** [douglascrockford/JSON-java#166]
When we are using, it happened that keyNames in out JSON contained $ character. When this JSON was converted to XML, it puts those characters unmodified as xml node name, which makes xml invalid. Please remove invalid characters from xml node names when converting from JSON to xml.

**Comment by stleary** [comment]
Unless the JSON started out as valid XML and then became invalid after processing by JSON-java, this sounds like a problem with your input data. Can you provide a snippet of the data? Please also include the API methods used to pass the data to JSON-java, and how it is retrieved.

**Comment by johnjaylward** [comment]
also see #138 and #123 for similar issues as well.

**Comment by stleary** [comment]
As previously noted, our choices are to throw an exception or leaving the code in place. No changes are planned for this issue at the present time.
