### ISSUE TITLE
ClassCastException in JSONObject.valueToString()

### ISSUE THREAD

**Issue by stleary** [douglascrockford/JSON-java#167]
JSONObject.valueToString(Object) is a public static method. It is expected, but not required, that it will only be called for JSONObject values. The following code will result in a ClassCastException in the JSONObject(Map&lt;String, Object>) constructor:

        Map<Integer, String> myMap = new HashMap<Integer, String>();
        myMap.put(1,  "myValue");
        String str = JSONObject.valueToString(myMap);

**Comment by johnjaylward** [comment]
Yes, this should be fixed in #153 as well I think. The root cause is the same. I was unfamiliar with this method though.

The proper cast would be
* ```Map<?, ?> map = (Map<?, ?>) value```
* ```Collection<?> coll = (Collection<?>) value```

If I recall, this was already fixed in #153, but if not should be included there.

**Comment by stleary** [comment]
Confirmed fix in https://github.com/stleary/JSON-Java-unit-test/tree/c578216844bc0293748318109a21fc755cdfc594
