### ISSUE TITLE
Implement an interface

### ISSUE THREAD

**Issue by deinok** [douglascrockford/JSON-java#171]
Please make an iterface to do things like this

    //Interface
    public interface JSONSerializable{
        JSONObject toJSONObject();
    }
    //JSONObject Class
    public JSONObject put(String key, JSONSerializable jsonSerializable){
        return put(key,jsonSerializable.toJSONObject());
    }
    //Exemple Class
    public class Foo implements JSONSerializable{
        int age;
        int name;
        public JSONObject toJSONObject(){
        //Your Implementation
        }
    }

**Comment by stleary** [comment]
Perhaps you can develop this idea a little more. For example,
* How does this help the developer?
* How does it interact with the current API? Does it break anything?
* Are you going to propose some unit tests?
* Should there be a JSONArraySerializable interface?
* JSONObject(JSONObjectSerializable) constructor?
* Any impact on the get() or opt() methods?
* Any use cases for other specialized classes (XML, etc)?

**Comment by deinok** [comment]
I have so much work this week, sorry.

I can send a pull with the changes with my full implemented idea and some UnitTests if you want.

**Comment by stleary** [comment]
No worries, respond when you have time.

**Comment by stleary** [comment]
Open a new issue or pull request when you have time to work on this.
