### ISSUE TITLE
latest jar 20150729 from Maven requires Java 8

### ISSUE THREAD

**Issue by watery** [douglascrockford/JSON-java#172]
The jar `json-20150729.jar` available at http://search.maven.org/#artifactdetails|org.json|json|20150729|jar requires JDK 8.

Is Java 8 really required for the code? Or can an additional Java 7 version be released?

**Comment by johnjaylward** [comment]
see #156 . This will be corrected in the next release

**Comment by watery** [comment]
Great, thank you!

I'll look forward for it.
