### ISSUE TITLE
New Maven release request for 20151123

### ISSUE THREAD

**Issue by stleary** [douglascrockford/JSON-java#176]
@BGehrels, will you please release https://github.com/douglascrockford/JSON-java/releases/tag/20151123 to the Maven repository? Also, please delete the phrase "The package compiles on Java 1.2 thru Java 1.4." from the POM text.
Thanks,
Sean

**Comment by BGehrels** [comment]
done

**Comment by stleary** [comment]
Looks great, thanks!
