### ISSUE TITLE
Java8 Optional?

### ISSUE THREAD

**Issue by georgeyanev** [douglascrockford/JSON-java#177]
Hi,
Is there any plans to support the Optional type from java8 for return values of this opt methods you have?
So that I could for example do this

    Optional<String> streetName = obj.optJSONObject("person")
         .flatMap(person -> person.optJSONObject("address"))
         .flatMap(adr -> adr.optString("streetName"));
Instead of checking for null values after every opt method?

**Comment by johnjaylward** [comment]
not at this time. we are currently supporting java 7 for android support
