### ISSUE TITLE
XML to JSON based on XSD

### ISSUE THREAD

**Issue by mohitjagtiani** [douglascrockford/JSON-java#178]
I have an xml with number of repeating elements/sub-elements. I wish to convert the XML to JSON object such that if element is repeating in xsd it is converted to JSON Array and normal JSON property.
E.g.
`<Test>
  <Elements>
     <Element>
        <Item>1</Item>
     </Element>
      <Element>
        <Item>2</Item>
     </Element>
  </Elements>
</Test>`
will give:
`{
"Test": {
"Elements": {
"Element": [
{ "Item": "1" },
{ "Item": "2" }
]
}
}
}`

and
`<Test>
  <Elements>
     <Element>
        <Item>1</Item>
     </Element>
  </Elements>
</Test>`

should also give
`{
"Test" : {
"Elements" : {
"Element" : [{
"Item" : "1"
}
]
}
}
}`

and not
`{
"Test": {
"Elements": {
"Element": { "Item": "1" }
}
}
}`

I used JSONML toJSONML method but with no success. Is there any key word which I can use in repeating XML elements to distinguish?
My calling statement is : JSONObject output = XML.toJSONObject(input); where input in XML string that I pass.

**Comment by mohitjagtiani** [comment]
not sure why example xml is not visible

**Comment by mohitjagtiani** [comment]
<Test>
  <Elements>
     <Element>
        <Item>1</Item>
     </Element>
      <Element>
        <Item>2</Item>
     </Element>
  </Elements>
</Test>

**Comment by johnjaylward** [comment]
you need to escape code like xml with back ticks
see https://help.github.com/articles/markdown-basics/#code-formatting 

```xml
<someXml />
 ```

**Comment by mohitjagtiani** [comment]
thanks, now answer to my real question? :)

**Comment by johnjaylward** [comment]
Currently the parser is very simple. It does not read XSD or anything other than the XML document itself. Because of this, it does not know if a single element should belong to an array or a single property.

the exact code that performs this is:
https://github.com/douglascrockford/JSON-java/blob/master/XML.java#L231
``` java
jsonobject.accumulate(string,
                                XML.stringToValue((String)token));
```

The accumulate method first creates a single property on the json object. If it's called again with the same key, it deletes the key and reinserts it as a JSONArray with the original value and the new value.

**Comment by mohitjagtiani** [comment]
ok, is there any other way or utility to achieve the desired result?

**Comment by johnjaylward** [comment]
https://github.com/FasterXML/jackson is a larger library with a lot more customability. This also makes it more complex to configure and use. However, it's XML support is very comprehensive.

**Comment by mohitjagtiani** [comment]
thanks John. I for now used https://github.com/bramstein/xsltjson. Which inturn is using json.org jars but little differently I guess

**Comment by jaganch** [comment]
Hi Mohit,

I have the same problem now. Can you please elaborate on how you solved this problem? Any code snippet.
