### ISSUE TITLE
JSONString to Object

### ISSUE THREAD

**Issue by bes1002t** [douglascrockford/JSON-java#182]
Hi, 

is it possible to use your code to get a object from a JSONObject?

e.g. convert a object from with type Message to a JSONObject, send it to another PC and then use this JSONObject to get an instance of a Message, filled with all sent values.

thanks

**Comment by johnjaylward** [comment]
it will convert a valid JSON string to a JSONObject or JSONArray. You can then use the JSONObject and JSONArray properties to re-populate your objects. If you are looking for a more automated solution I usually recommend Jackson, but there are other out there that use annotations or xml config files to know how to repopulate the serialized objects.

**Comment by bes1002t** [comment]
thanks for that really fast reply,

I will take a look at jackson and gson, thx :)
