### ISSUE TITLE
  How can i pass the folder path in the JSON object

### ISSUE THREAD

**Issue by bmadhu226** [douglascrockford/JSON-java#183]
How can i pass the folder path in the JSON.

But when passing the path("/latest/object/300000006637803/child/child_c ) to JSON it reading as "\/latest\/MetaData_c\/300000006637803\/child\/MetaDataFieldsCollection_c"

code:

part=new LinkedHashMap();
part.put("id",count);
part.put("path","/latest/object/300000006637803/child/child_c);
part.put("operation",operation);
System.out.println(JSONValue.toJSONString(part));

output:

{

"id":"part1",

"path":"\/latest\/MetaData_c\/300000006637803\/child\/MetaDataFieldsCollection_c",

"operation":"create"

}

**Comment by stleary** [comment]
Could you please clarify your code example? The JSON-java project has no JSONValue class.
