### ISSUE TITLE
Make JSONObject.write(Writer writer, int indentFactor, int indent) public

### ISSUE THREAD

**Issue by jpfiset** [douglascrockford/JSON-java#184]
Would it be possible to change the signature of JSONObject.write(Writer writer, int indentFactor, int indent) to public?

Currently, if I which to send formatted JSON to a stream, I need to first convert it to a String (toString(3)) and then send the string to the stream. It would be more efficient to send directly to the stream.

**Comment by stleary** [comment]
JSONObject.write(Writer, int, int) outputs the contents of the JSONObject to a Writer. I don't think you could use it, per your example, to output an int value not already contained by the JSONObject to a Writer. If you just want a convenient way to output a JSONObject to a Writer, then JSONObject.write(Writer) is already available for that purpose, without the need to pass indent params. But you may not be referring to the JSONObject when you say, "send formatted JSON to a stream". Can you clarify your use case with a code fragment that shows how your code works now, and how you would like it to work?

**Comment by johnjaylward** [comment]
I believe @jpfiset is trying to do something similar to this:
```java
    protected static void writeJsonObject(final HttpServletResponse response, final JSONObject jsonObject)
            throws IOException, JSONException {
        try (final PrintWriter writer = response.getWriter()) {
            response.setContentType("application/json");
            try {
                if (LOG.isTraceEnabled()) {
                    jsonObject.write(writer, TRACE_INDENT);
                } else {
                    jsonObject.write(writer);
                }
            } catch (final JSONException ex) {
.....
```

I modified my local copy to have that public method.

 @jpfiset request isn't to output an ```int```, but to output the entire JSONObject to a non-string writer while specifying the indent size.

**Comment by johnjaylward** [comment]
To be clear, I don't think it makes sense to make the 3 parameter method public. Having a new public method like I did is probably a slightly cleaner solution.

**Comment by stleary** [comment]
Seems straightforward. No objection here to expanding the API in that manner. Let's see if anyone else has an opinion.

**Comment by jpfiset** [comment]
@johnjaylward, thanks for the explanation.

**Comment by stleary** [comment]
See https://github.com/douglascrockford/JSON-java/pull/185
